# Generated by Django 5.2.8 on 2025-11-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Revisión'), ('active', 'Activo'), ('rejected', 'Rechazado'), ('archived', 'Archivado')], default='active', max_length=10, verbose_name='Estatus'),
        ),
    ]
