# Generated by Django 5.2.8 on 2025-11-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen del Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Revisión'), ('active', 'Activo'), ('rejected', 'Rechazado')], default='active', max_length=10, verbose_name='Estatus'),
        ),
    ]
