# Generated by Django 5.2.8 on 2025-11-06 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VENDOR_APPROVED', 'Vendedor Aprobado'), ('VENDOR_REJECTED', 'Vendedor Rechazado'), ('PRODUCT_APPROVED', 'Producto Aprobado'), ('PRODUCT_REJECTED', 'Producto Rechazado'), ('ORDER_STATUS_CHANGED', 'Estado de Pedido Cambiado'), ('USER_REGISTERED', 'Usuario Registrado'), ('USER_LOGIN', 'Inicio de Sesión'), ('PRODUCT_CREATED', 'Producto Creado'), ('ORDER_CREATED', 'Pedido Creado')], max_length=50, verbose_name='Acción')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detalles')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
