# Generated by Django 5.2.8 on 2025-11-06 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('vendor', 'Vendedor'), ('client', 'Cliente')], default='client', max_length=10, verbose_name='Rol')),
                ('vendor_status', models.CharField(blank=True, choices=[('pending', 'Pendiente de Aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], max_length=10, null=True, verbose_name='Estatus de Vendedor')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('store_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Tienda')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
