# Generated by Django 5.2.8 on 2025-11-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='profile',
            name='control_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Control'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
