# Generated by Django 5.2.8 on 2025-11-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Está Baneado'),
        ),
    ]
