# Generated by Django 5.2.8 on 2025-12-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='reports/evidence/', verbose_name='Evidencia (Captura)'),
        ),
    ]
